version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      core:
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: daily
    groups:
      website:
        update-types:
          - "major"
          - "minor"
          - "patch"
